### ISSUE TITLE
Cross-browser

### ISSUE THREAD

**Issue by EmirGluhbegovic** [sautumn/material-ui-autocomplete-google-places#12]
DISCLAIMER: I am not entirely sure if this is a material-ui autocomplete issue or a material-ui-autocomplete-google-places issue.

The plugin works on google chrome on the laptop but nothing happens on Safari, chrome on mobile or safari on mobile. 

Any suggestions?

**Comment by archcorsair** [comment]
Apologies, the package maintainers have not been able to work on this package in some time. However there are plans for a complete rewrite & support for latest MUI 
very soon. Good luck & sorry for the inconvenience!
