### ISSUE TITLE
Change import type from material-ui

### ISSUE THREAD

**Issue by tomjohnneill** [sautumn/material-ui-autocomplete-google-places#14]
At the moment the import statement from material-ui is:
`import { AutoComplete, MenuItem } from 'material-ui';`

As far as I understand it, this imports all of material-ui - rather than just the components needed. (see the first answer here: https://stackoverflow.com/questions/41333561/reactjs-material-ui-app-is-whooping-917kb-in-production-build-what-do-i-do-to-d)

I think this should this be changed to:

`import AutoComplete from 'material-ui/AutoComplete';`
`import MenuItem from 'material-ui/MenuItem';`

**Comment by archcorsair** [comment]
Apologies, the package maintainers have not been able to work on this package in some time. However there are plans for a complete rewrite & support for latest MUI 
very soon. Good luck & sorry for the inconvenience!
