### ISSUE TITLE
"import GooglePlaceAutocomplete" itself throws error

### ISSUE THREAD

**Issue by 462960** [sautumn/material-ui-autocomplete-google-places#17]
Console shows in red "Uncaught TypeError: Cannot read property 'object' of undefined".
Is it intended to work with React 16?
CLI shows the whole bunch of warnings. Three of them require previous versions of React, ReactDOM, material-ui and the next one requires react-tap-event-plugin.

**Comment by yosefprogramming** [comment]
I get this issue too. Not sure how to solve it.

**Comment by archcorsair** [comment]
Hi all, we’ve not really been maintaining this package as much as we’d like to. I’m currently traveling, when I get home I will debug and fix this.  Sorry for the issues

**Comment by archcorsair** [comment]
This is fixed in release 2.3.0
