### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kesla** [sautumn/material-ui-autocomplete-google-places#18]
Hey!

Nice lib!!

However, currently I'm blocked by PropTypes not being available - but that seems to have been fixed already in master! Any chance you'd be interested in releasing this lib? Thanks!

**Comment by archcorsair** [comment]
Apologies, the package maintainers have not been able to work on this package in some time. However this are plans for v2 sometime soon. Good luck & sorry for the inconvenience!
