### ISSUE TITLE
Remove injectTapEventPlugin() from the library code

### ISSUE THREAD

**Issue by Pgsuarez** [sautumn/material-ui-autocomplete-google-places#5]
It crashes the app

Error: injectTapEventPlugin(): Can only be called once per application lifecycle.

It is recommended to call injectTapEventPlugin() just before you call 	ReactDOM.render(). If you are using an external library which calls injectTapEventPlugin() 	itself, please contact the maintainer as it shouldn't be called in library code and 	should be injected by the application.

**Comment by archcorsair** [comment]
I'm assuming you're using `injectTapEventPlugin()` in your project somewhere.
We'll do some testing and see if we can remove it form the component. Thanks for bringing this to our attention.

**Comment by keithamoss** [comment]
@sautumn The version published to npm (2.0.0) still appears to have `injectTapEventPlugin()` in `lib/index.js`. I'm guessing this is just a matter of yourself needing to bump the version number in `package.json` and republish to npm?

<img width="783" alt="screen shot 2017-05-23 at 18 50 04" src="https://cloud.githubusercontent.com/assets/1672960/26351115/a971043e-3fe8-11e7-9e5a-77e529905fd1.png">

(This Node/npm newbie has poked around and tried to install it directly from GitHub, but couldn't get building working [issues with Babel and `ReferenceError: Unknown plugin "transform-es2015-destructuring"`].)

**Comment by archcorsair** [comment]
Huh, that's odd. Version was major bumped and this change should have been included. Looking into it

**Comment by archcorsair** [comment]
Should be fixed now, you can avoid caching issues with

`npm i material-ui-autocomplete-google-places@latest -S`
