### ISSUE TITLE
Text display not updating

### ISSUE THREAD

**Issue by katbusch** [sautumn/material-ui-autocomplete-google-places#6]
When I tried to use this exactly as in the example with material-ui version 17.4, the search box is empty even when you type in it.  I debugged a little and saw that when `updateInput` is being called, the first parameter is the react component, so the the `this` isn't being bound correctly.  The second parameter is actually the text that was typed.

**Comment by sautumn** [comment]
Hey katbusch! Sorry! I can't seem to reproduce this error. Do you mind pasting your code? I just tested it again and it seems to be working fine for me. This is what my react component looks like: 

```js
import React from 'react';
import ReactDOM from 'react-dom';

import GooglePlaceAutocomplete from 'material-ui-autocomplete-google-places';

//For GooglePlaceAutocomplete package
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme'

class Main extends React.Component {
  constructor(props){
    super(props);
  }

  getCoords(lat, lng){
    console.log(lat, lng);
  }

  render() {
    return (
      <MuiThemeProvider muiTheme={getMuiTheme()}>
        <GooglePlaceAutocomplete
        // Function to return lat and lng
        floatingLabelText={'Input location here'}
        results={this.getCoords}
          />
      </MuiThemeProvider>
    );
  }
}

ReactDOM.render(
  <Main />,
  document.getElementById('app')
);
```
and my html:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
</head>
<body>
  <div id="app"></div>
   <script type="text/javascript" src="./compiled/bundle.js" charset="utf-8"></script>
</body>
</html>
```

and my dependencies from my package.json:

```js
  "dependencies": {
    "material-ui": "^0.18.1",
    "material-ui-autocomplete-google-places": "^2.0.0",
    "path": "^0.12.7",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-tap-event-plugin": "^2.0.1",
    "webpack": "^2.4.1"
  },
```

and then finally the live page looks like: 

<img width="672" alt="screen shot 2017-05-20 at 6 08 28 pm" src="https://cloud.githubusercontent.com/assets/7321716/26280412/770e9e42-3d87-11e7-8262-21f6071e6e03.png">

**Comment by archcorsair** [comment]
I can't reproduce this issue either

**Comment by keithamoss** [comment]
For anyone else that may happen across this issue - I managed to reproduce it by running a version of `material-ui` < 0.18.0.

From a cursory glance of the [release notes](https://github.com/callemall/material-ui/releases/tag/v0.18.0) for 0.18.0 I expect https://github.com/callemall/material-ui/pull/6621 was the culprit.
