### ISSUE TITLE
filling in field on load

### ISSUE THREAD

**Issue by EmirGluhbegovic** [sautumn/material-ui-autocomplete-google-places#9]
Hey,

I want to automatically fill in the text field when the component mounts. I am getting back the string from another plugin of the user current location and now I want to insert that text into the GooglePlaceAutocomplete component. 

I tried setting searchText but nothing. Any suggestions?

**Comment by bmkrocks1** [comment]
My suggestion is to expose the searchText property in GooglePlaceAutocomplete component.

At [line 84](https://github.com/sautumn/material-ui-autocomplete-google-places/blob/master/src/index.js#L84):

`searchText={this.state.searchText || this.props.searchText}`

**Comment by archcorsair** [comment]
Apologies, the package maintainers have not been able to work on this package in some time. However there are plans for a complete rewrite & support for latest MUI 
very soon. Good luck & sorry for the inconvenience!
